title: Instacart Market Basket Analysis
description: 
#theme: just-the-docs
remote_theme: hydecorp/hydejack@v9

url: https://xgui17.github.io/Instacart-Basket-Analysis/

# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME